### PR TITLE
Fix timeouts when df is being run

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Comment by itkovian** [comment]
Also contains upstream fixes into master.

**Comment by wdpypere** [comment]
I like this, but I might be missing 2 things here
 - a version bump of some sort?
 - the check_group_user thing that needs to be fixed, or is that going to be a separate PR?

**Comment by itkovian** [comment]
The version bump resides in the timestamp and the git commit ID. I prefer keeping the version the same as upstream.

**Comment by itkovian** [comment]
I propose we keep the check_group_user thing for another PR.

**Pull request merged**
