### PR TITLE
Restore PTPD check (HPC-7253)

### PR DESCRIPTION
**Pull request by itkovian**

### CODE REVIEW

**Comment by stdweird** [comment]
@itkovian version bump?

**Comment by itkovian** [comment]
The version of the build has the git commit, like
~~~~
lbnl-nhc-1.4.2-0.47.g4bd8afc.el7.ug.noarch
~~~~

The major, minor, patch numbers track upstream.

**Comment by itkovian** [comment]
Hmm, I should check if this is monotonically rising.

**Comment by itkovian** [comment]
This build would become `lbnl-nhc-1.4.2-0.53.gca11e72.el7.ug.x86_64`

**Comment by wdpypere** [comment]
no version bump?

**Pull request merged**
